steps:
  # This run a validation on the logstash configuration
- name: docker.elastic.co/logstash/logstash:${_ELK_VERSION}
  id: pipeline-test
  script: |
    #!/usr/bin/env bash
    cp ./logstash/config/pipelines.yml /usr/share/logstash/config/pipelines.yml
    cp -R ./logstash/pipeline/ /usr/share/logstash/pipeline/
    cp -R ./logstash/scripts/ /usr/share/logstash/scripts/
    logstash --config.test_and_exit --debug -f '/usr/share/logstash/pipeline/debug_logs/'
    exit_code=$?
    test $exit_code -eq 0 && exit 0 || exit 1
