steps:
  # This run a validation on the logstash configuration
- name: docker.elastic.co/logstash/logstash:${_ELK_VERSION}
  id: pipeline-test
  script: |
    #!/usr/bin/env bash
    mkdir -p /usr/share/logstash/scripts/debug_logs
    ln -s /usr/share/logstash/scripts/debug_logs/duration_parse.rb /workspace/logstash/scripts/debug_logs/duration_parse.rb
    logstash --config.test_and_exit -f logstash/pipeline/debug
    exit_code=$?
    test $exit_code -eq 0 && exit 0 || exit 1
